 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: sharedbook-deployment
 spec:
   selector:
     matchLabels:
       app: sharedbook-pod
   template:
     metadata:
       labels:
         app: sharedbook-pod
     spec:
       containers:
       - name: sharedbook-container 
         image: netproregs.azurecr/sharedbook-aspnetcore:v1
         resources:
           limits:
             memory: "128Mi"
             cpu: "500m"
         ports:
         - containerPort: 80
 